dist: xenial
language: node_js
node_js: "12"
sudo: required

matrix:
  fast_finish: true
  include:
    # JS Build
    - env: TEST=JS 

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
  homebrew:
    update: true
    packages:
      - python
      - python2
      - pybind11
      - cmake

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then npm install -g yarn; fi

install:
  - node --version
  - yarn

script:
  - if [ "$TEST" = "JS" ]; then yarn lint && yarn test; fi
